### ISSUE TITLE
Suggestion: prefix all commands with a meaningful prefix

### ISSUE THREAD

**Issue by jesperronn** [kevinsimper/gcphelp-cli#1]
One suggestion: Prefix the commands, to increase further discoverability gc-account, gc-project, etc. You should do that with a meaningful prefix

example:
```
$ gcphelp - show available commands
$ gcpaccount - switch easily between accounts
$ gcpproject - switch easily between projects
$ gcpcluster - switch easily between Kubernetes clusters
$ gcpnamespace - switch easily between Kubernetes namespaces on the active cluster
```

**Comment by kevinsimper** [comment]
That is a good idea, then if you want to simplify them even further you can do so in your .bashrc file 👍

**Comment by kevinsimper** [comment]
@jesperronn It is published now in the latest release 😄 https://github.com/kevinsimper/gcphelp-cli/releases/tag/v1.2.0
